adapter:
  host: http://localhost
  port: 3004
  base: ''
  resources:
    invoke: '/ethereum/smartcontracts/invoke/__ADDRESS_OR_ALIAS__'
    register: '/ethereum/smartcontracts/register'
    balance: '/ethereum/balance/__ADDRESS__'
    transfer: '/ethereum/transfers'
    token:
      register: '/ethereum/token/register'
      transfer: '/ethereum/token/__ADDRESS_OR_ALIAS__/transfer'
      transferFrom: '/ethereum/token/__ADDRESS_OR_ALIAS__/transferFrom'
      balance: '/ethereum/token/__ADDRESS_OR_ALIAS__/balanceOf/__ADDRESS__'
      metadata: '/ethereum/token/__ADDRESS_OR_ALIAS__/metadata'
      approve: '/ethereum/token/__ADDRESS_OR_ALIAS__/approve'
      allowance: '/ethereum/token/__ADDRESS_OR_ALIAS__/allowance'
    encode: '/protocol/encode'
    decode: '/protocol/decode'
wallet:
  host: http://localhost
  port: 3002
  base: ''
  resources:
    signTx: '/ethereum/sign-tx'
    sendTx: '/ethereum/send-tx'
    sendSignedTx: '/ethereum/send-signed-tx'
broker:
  host: ws://localhost
  port: 3001
  base: ''
  resources:
    events: '/ethereum/subscribe?address=__ADDRESS__&sender=__SENDER__&consumer=__CONSUMER__'
