adapter:
  host: http://localhost
  port: 3004
  base: ''
  resources:
    deploy: '/__DLT__/smartcontracts/deploy'
    invoke: '/__DLT__/smartcontracts/invoke/__ADDRESS_OR_ALIAS__'
    invokeAbi: '/__DLT__/smartcontracts/invoke/abi'
    register: '/__DLT__/smartcontracts/register'
    findAll: '/__DLT__/smartcontracts'
    balance: '/__DLT__/balance/__ADDRESS__'
    transfer: '/__DLT__/transfers'
    token:
      register: '/__DLT__/token/register'
      transfer: '/__DLT__/token/__ADDRESS_OR_ALIAS__/transfer'
      transferFrom: '/__DLT__/token/__ADDRESS_OR_ALIAS__/transferFrom'
      balance: '/__DLT__/token/__ADDRESS_OR_ALIAS__/balanceOf/__ADDRESS__'
      metadata: '/__DLT__/token/__ADDRESS_OR_ALIAS__/metadata'
      approve: '/__DLT__/token/__ADDRESS_OR_ALIAS__/approve'
      allowance: '/__DLT__/token/__ADDRESS_OR_ALIAS__/allowance'   
      findAll: '/__DLT__/token'    
    encode: '/protocol/encode'
    decode: '/protocol/decode'
wallet:
  host: http://localhost
  port: 3002
  base: ''
  resources:
    signTx: '/__DLT__/sign-tx'
    sendTx: '/__DLT__/send-tx'
    sendSignedTx: '/__DLT__/send-signed-tx'
broker:
  host: ws://localhost
  port: 3001
  base: ''
  resources:
    events: '/__DLT__/subscribe?address=__ADDRESS__&sender=__SENDER__&consumer=__CONSUMER__&status=__STATUS__'
