adapter:
  host: http://localhost
  port: 3004
  base: ''
  resources:
    invoke: '/ethereum/smartcontracts/__ADDRESS__'
    register: '/ethereum/smartcontracts/register'
    balance: '/ethereum/balance/__ADDRESS__'
    transfer: '/ethereum/transfers'
    tokenRegister: '/ethereum/token/register'
    tokenTransfer: '/ethereum/token/__ADDRESS_OR_ALIAS__/transfer'
    tokenBalance: '/ethereum/token/__ADDRESS_OR_ALIAS__/balance/__ADDRESS__'
    tokenMetadata: '/ethereum/token/__ADDRESS_OR_ALIAS__/metadata/'
    encode: '/protocol/encode'
    decode: '/protocol/decode'
wallet:
  host: http://localhost
  port: 3002
  base: ''
  resources:
    signTx: '/ethereum/sign-tx'
    sendTx: '/ethereum/send-tx'
    sendSignedTx: '/ethereum/send-signed-tx'
broker:
  host: ws://localhost
  port: 3001
  base: ''
  resources:
    events: '/ethereum/subscribe?address=__ADDRESS__&sender=__SENDER__&consumer=__CONSUMER__'
