adapter:
  host: https://kong-blockchainhub-demo.kickstartteam.es
  port: ''
  base: '/v1/dlt-adapter'
wallet:
  host: https://kong-blockchainhub-demo.kickstartteam.es
  port: ''
  base: '/v1/wallet-hub'
broker:
  host: ws://hancock-dlt-broker-blockchainhub-demo.kickstartteam.es
  port: 80
  base: ''