adapter:
  host: http://mockAdapter
  port: 6666
  base: '/mockBase'
  resources:
    invoke: '/mockInvoke/__ADDRESS__'
    register: '/mockRegister'
    balance: '/mockBalance/__ADDRESS__'
    transfer: '/mockTransfer'
    tokenRegister: '/mockToken/mockRegister'
    tokenTransfer: '/mockToken/__ADDRESS_OR_ALIAS__/mockTransfer'
    tokenTransferFrom: '/mockToken/__ADDRESS_OR_ALIAS__/mockTransferFrom'
    tokenBalance: '/mockToken/__ADDRESS_OR_ALIAS__/mockBalance/__ADDRESS__'
    tokenMetadata: '/mockToken/__ADDRESS_OR_ALIAS__/mockMetadata'
    tokenAllowance: '/mockToken/__ADDRESS_OR_ALIAS__/mockAllowance'
    encode: '/mockEncode'
    decode: '/mockDecode'
wallet:
  host: http://mockWallet
  port: 6666
  base: '/mockBase'
  resources:
    signTx: '/mockSignTx'
    sendTx: '/mockSendTx'
    sendSignedTx: '/mockSendSignedTx'
broker:
  host: ws://mockBroker
  port: 6666
  base: '/mockBase'
  resources:
    events: '/mockEvents?address=__ADDRESS__&sender=__SENDER__&consumer=__CONSUMER__'
